---
# tasks file for nginx

- name: Install nginx
  become: yes
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes
    
- name: Index page
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    
- name: replace default nginx
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart service nginx
