---
# tasks file for nginx

- name: Install nginx
  become: yes
  ansible.builtin.apt:
    name: nginx
    state: latest
    
- name: Start service nginx
  service:
      name: nginx
      state: started
      enabled: yes

- name: replace default nginx config
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart service nginx
