---
# tasks file for nginx

- name: Install nginx
  become: yes
  ansible.builtin.apt:
    name: nginx
    state: latest
    
# - name: Index page
#  ansible.builtin.copy:
#    src: index.html
#    dest: /var/www/html/index.html
    
- name: replace default nginx config
  ansible.builtin.template:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart service nginx
