---
  - name: Install InfluxDB exporter
    ansible.builtin.get_url:
      url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
      dest: /usr/local/bin/influxdb_stats_exporter
      mode: 0555

  - name: Create influxdb_stats_exporter service
    ansible.builtin.copy:
      src: prometheus-influxdb-stats-exporter.service
      dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
    notify:
      - Reload systemd
      - Restart influxdb_stats_exporter

  - name: influxdb_stats_exporter service
    ansible.builtin.service:
      name: prometheus-influxdb-stats-exporter.service
      state: started
      enabled: yes
