---
  - name: Add an apt signing key for influxdb
    ansible.builtin.apt_key: 
        url: https://repos.influxdata.com/influxdb.key

  - name: Add influxdb repo
    ansible.builtin.apt_repository:
        repo: deb https://repos.influxdata.com/ubuntu focal stable
  
  - name: Install influxdb package
    apt:
        name: influxdb

  - name: Copy conf influxdb
    ansible.builtin.copy:
      src: influxdb.conf
      dest: /etc/influxdb/influxdb.conf
    notify: Restart influxdb  

  - name: Start service influxdb
    service:
        name: influxdb
        state: started
        enabled: yes

  - name: Install telegraf
    ansible.builtin.apt:
      name: telegraf

  - name: Copy conf telegraf
    ansible.builtin.copy:
      src: telegraf.conf
      dest: /etc/telegraf/telegraf.conf
    notify: Restart telegraf

  - name: Start telegraf
    ansible.builtin.service:
      name: telegraf
      state: started
      enabled: yes
