--- 
  - name: Create grafana directories
    ansible.builtin.file:
      path: "/opt/grafana/provisioning/{{ item }}"
      state: directory
      recurse: yes
    loop:
      - dashboards
      - datasources

  - name: Setup Default datasource
    ansible.builtin.template:
      src: sample.yaml.j2
      dest: /opt/grafana/provisioning/datasources/sample.yaml

  - name: Setup influxdb datasource
    ansible.builtin.template:
      src: influxdb.yaml.j2
      dest: /opt/grafana/provisioning/datasources/influxdb.yaml
  
  - name: Setup rsyslog telegraf datasource
    ansible.builtin.template:
      src: rsyslog.yaml.j2
      dest: /opt/grafana/provisioning/datasources/rsyslog.yaml
  
  - name: Copy conf for dashboards
    ansible.builtin.template:
      src: dashboard.yaml.j2
      dest: /opt/grafana/provisioning/dashboards/sample.yaml

  - name: Setup dashboard main
    ansible.builtin.copy:
      src: main.json
      dest: /opt/grafana/provisioning/dashboards/main.json

  - name: Setup dashboard telegraf rsyslog
    ansible.builtin.copy:
      src: rsyslog.json
      dest: /opt/grafana/provisioning/dashboards/rsyslog.json 
    
  - name: Setup dashboard telegraf mysql
    ansible.builtin.copy:
      src: mysql.json
      dest: /opt/grafana/provisioning/dashboards/mysql.json 

  - name: Copy config for grafana
    ansible.builtin.template:
        src: grafana.ini.j2
        dest: /opt/grafana/grafana.ini   
    no_log: true

  - name: Install and start grafana in Docker
    community.docker.docker_container:
      name: grafana
      image: grafana/grafana
      volumes: /opt/grafana:/etc/grafana
      published_ports: "{{ grafana_port }}:3000"
      restart_policy: always
      container_default_behavior: no_defaults
