---
# tasks file for uwsgi

- name: Install uswgi part 1
  become: yes
  ansible.builtin.apt:
    name: uwsgi
    state: latest

    
- name: Install uswgi plugin python3
  become: yes
  ansible.builtin.apt:
    name: uwsgi-plugin-python3
    state: latest
    
    
- name: Start service uwsgi
  ansible.builtin.service:
    name: uwsgi
    state: started
    
- name: template file agama.ini
  ansible.builtin.template:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart service uwsgi
    
