{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HAProxy (containers)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "haproxy_server_up" }
   ]
  },
  {
   "title": "HAProxy status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "Bind status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "Bind",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{type=\"A\"}[1m])"
    }
   ]
  },
  {
   "title": "Nginx ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Nginx status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up" }
   ]
  },
  {
   "title": "influxdb status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success"
    }
   ]
  },
  {
   "title": "InfluxDB ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[5m])"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[1m])"
    }
   ]
  },
  {
   "title": "MySQL status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "Keepalived status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "keepalived_up" }
   ]
  },
  {
   "title": "Keepalived",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state" }
   ]
  },
  {
   "title": "Pinger",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100)"
    }
   ]
  }
 ]
}