---
  - name: Create the directory
    ansible.builtin.file:
      path: /opt/agama
      state: directory

  - name: Install application
    get_url:
        url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
        dest: /opt/agama/Dockerfile


  - name: Download agama application
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
      dest: /opt/agama/agama.py


  - name: Build docker image
    community.docker.docker_image:
      name: agama
      source: build
      build:
        path: /opt/agama

  - name: Install and start agama in Docker
    community.docker.docker_container:
      name: agama
      image: agama
      published_ports: "{{ agama_port }}:8000"
      container_default_behavior: no_defaults
      env:
       AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
       

  - name: Install and start second agama in Docker
    community.docker.docker_container:
      name: agama2
      image: agama
      published_ports: "{{ second_agama_port }}:8000"
      container_default_behavior: no_defaults
      env:
       AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}
