---
# tasks file for backup

  - name: Create user backup with ssh key
    ansible.builtin.user:
      name: backup
      home: /home/backup
      shell: /bin/bash
      generate_ssh_key: yes

  - name: Create the directory
    ansible.builtin.file:
      path: /home/backup/restore
      state: directory
      owner: backup
      group: backup
      mode: 0755
  
  - name: Install duplicity
    ansible.builtin.apt:
      name: duplicity

  - name: Create a file
    ansible.builtin.template:
      src: known_hosts.j2
      dest: /home/backup/.ssh/known_hosts
      owner: backup
