---
  - name: Stop systemd-resolved
    service:
        name: systemd-resolved
        state: stopped
        enabled: no 
        
  - name: Add resolv configuration
    ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
