---
# tasks file for users

-name: create juri user
user:
  name: juri
  
-name: create roman user
user:
  name: roman
  
  
-name: Set authorized keys taken from url using lookup
  ansible.posix.authorized_key:
    user: juri
    state: present
    key: "{{ lookup('url', 'https://github.com/hudolejev.keys', split_lines=False) }}"
    
-name: Set authorized keys taken from url using lookup
  ansible.posix.authorized_key:
    user: roman
    state: present
    key: "{{ lookup('url', 'https://github.com/romankuchin.keys', split_lines=False) }}"
