---
# tasks file for users

- name: Add the user JURI
  ansible.builtin.user:
    name: juri
    
- name: Add the user Roman
  ansible.builtin.user:
    name: roman
    
- name: Set authorized keys taken from url of "JURI"
  ansible.posix.authorized_key:
    user: juri
    key: "{{ lookup('url', 'https://github.com/hudolejev.keys', split_lines=False) }}"
    
- name: Set authorized keys taken from url of "Roman"
  ansible.posix.authorized_key:
    user: roman
    key: "{{ lookup('url', 'https://github.com/romankuchin.keys', split_lines=False) }}"
