- name: juri
  ansible.builtin.user:
    name: juri
    comment: Juri Hudolejev
  ansible.posix.authorized_key:
    key: https://github.com/hudolejev.keys
  
 
- name: roman
  ansible.builtin.user:
    name: roman
    comment: Roman Kuchin
  ansible.posix.authorized_key:
    key: https://github.com/romankuchin.keys
