---
# tasks file for bind_exporter

  - name: Install bind9 exporter
    apt:
        name: prometheus-bind-exporter
        state: present

  - name: Start bind9 exporter
    service:
        name: prometheus-bind-exporter
        state: started
        enabled: yes
