---
# tasks file for keepalived

  - name: Install keepalived package
    ansible.builtin.apt:
        name: keepalived

  - name:  Start service keepalived
    ansible.builtin.service:
        name: keepalived
        state: started
        enabled: yes  

  - name: Place keepalived_script
    ansible.builtin.template:
      src: keepalived_script.j2
      dest: /home/keepalived_script
      mode: 777
    notify: restart keepalived

  - name: Copy conf for keepalived
    ansible.builtin.template:
      src: keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
    notify: restart keepalived
