---
  - name: Download keepalived-exporter
    ansible.builtin.unarchive:
      src: https://github.com/cafebazaar/keepalived-exporter/releases/download/v1.1.0/keepalived-exporter-1.1.0.linux-amd64.tar.gz
      dest: /usr/local/bin/
      remote_src: yes

  - name: Create keepalived exporter service
    ansible.builtin.copy:
      src: keepalived.service
      dest: /etc/systemd/system/keepalived-exporter.service
    notify:
      - Reload systemd
      - Restart keepalived

  - name: Start and enable
    ansible.builtin.service:
      name: keepalived-exporter
      state: started
      enabled: yes
