---
# tasks file for nginx_exporter

  - name: Install nginx exporter
    apt:
        name: prometheus-nginx-exporter
        state: present

  - name: Start nginx exporter
    service:
        name: prometheus-nginx-exporter
        state: started
        enabled: yes

