---
# handlers file for grafana

  - name: Restart grafana
    service:
        name: grafana-server
        state: restarted
  
  - name: Reset pass
    shell: |
      sleep 60
      grafana-cli admin reset-admin-password {{ grafana_pass }}
    no_log: true

