---
# tasks file for init

- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 86400
    
- name: Update CA certificates
  ansible.builtin.apt:
    name: ca-certificates>=20211000*
    
